pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('Django') {
      agent {
        docker { image 'gopikrishnayogeshwar/python-django-app:v3' }
      }
      steps {
        sh 'sudo docker run -d -p 8001:8001 gopikrishnayogeshwar/python-django-app:v3'
      }
    }
  }
}
