pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('Django') {
      agent {
        docker { image 'gopikrishnayogeshwar/flask-app:0.0.1' }
      }
      steps {
        sh 'docker run -d -p 5001:5001 gopikrishnayogeshwar/flask-app:0.0.1'
      }
    }
  }
}
